Repository deadlinks/cargo-deadlinks, pull requests merged in 2020-10, with the labels that each got.

#63 Use http HEAD method request instead of GET
  src/check.rs
Labels: A-http-check, enhancement

#67 Give a better error message if Cargo.toml is not present
  CHANGELOG.md
  src/main.rs
  tests/simple_project.rs
Labels: bug

#20 Improve display of findings
  src/lib.rs
  src/main.rs
  tests/simple_project.rs
  tests/simple_project/src/lib.rs
Labels: enhancement
