Repository deadlinks/cargo-deadlinks, pull requests merged in 2020-11, with the labels that each got.

#93 fix: correctly treat absolute paths against `dir`
  src/lib.rs
  src/parse.rs
Labels: bug

#95 Switch from reqwest to ureq
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/check.rs
Labels: A-http-check, enhancement

#98 Don't download dependencies from crates.io
  CHANGELOG.md
  src/main.rs
Labels: enhancement

#86 Switch from rcdom to lol_html
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  src/parse.rs
Labels: enhancement

#100 Improve handling of logging
  CHANGELOG.md
  src/main.rs
  tests/simple_project.rs
Labels: C-enhancement

#101 impl Default for CheckContext
  CHANGELOG.md
  src/check.rs
  src/lib.rs
Labels: C-enhancement

#103 Use MUSL for published linux binaries
  .github/workflows/deploy.yml
  CHANGELOG.md
Labels: C-enhancement

#108 feat: --ignore-fragments CLI parameter
  CHANGELOG.md
  src/bin/cargo-deadlinks.rs
  src/bin/deadlinks.rs
  src/check.rs
  src/lib.rs
Labels: C-enhancement, S-waiting-on-author

#121 Don't assume `/` is the directory separator
  CHANGELOG.md
  src/bin/cargo-deadlinks.rs
Labels: S-waiting-on-review

#122 Use 404 pages on example.com instead of a non-existent DNS
  tests/non_existent_http_link/src/lib.rs
Labels: A-http-check
